---
title: "NSCLC prognosis analysis"
author: "Yosuke Mizukami"
date: "2025-09-09"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r library, message=FALSE, warning=TRUE}
library(tidyverse)
library(readxl)
library(cowplot)
theme_set(theme_cowplot())
library(RColorBrewer)
library(logging)
library(GenomicRanges)
library(rtracklayer)
library(survival)
library(survminer)
library(ggsurvfit)
library(rlang)
library(patchwork)
```

```{r make directory}
# make directory
outdir0 <- "result/2_C_CAT/2_specific/4_prognosis/NSCLC"
outdir_table <- str_glue("{outdir0}/table")
dir.create(outdir_table, recursive = TRUE, showWarnings = FALSE)
outdir_pdf <- str_glue("{outdir0}/pdf")
dir.create(outdir_pdf, recursive = TRUE, showWarnings = FALSE)
```
```{r}
source("../../util/R/survival.R")
source("../../util/R/utils.R")
source("../../util/R/colors.R") 
source("../../util/R/readin.R")
```

```{r read data}
df_NSCLC <- df %>% 
  mutate(smoking_status_2groups = factor(smoking_status_2groups, levels = c("Never", "Ever"))) %>% 
  filter(PS_group != "NA") %>%
  filter(!is.na(OS_months) | OS_months != "NA") %>%
  filter(OS != "NA") %>%
  filter(cancertype_CCAT %in% c("LUAD", "LUSC")) %>%
  mutate(subtype = cancertype_CCAT) %>%
  mutate(cancertype_CCAT = case_when(
    subtype %in% c("LUAD", "LUSC") ~ "NSCLC",
    TRUE ~ subtype
  ))

df_NSCLCmut <- df_mut %>% 
  filter(Tumor_Sample_Barcode %in% df_NSCLC$Tumor_Sample_Barcode)

allsamples <- df_NSCLC %>% 
  pull(Tumor_Sample_Barcode)

never_samples <- df_NSCLC %>%
  filter(smoking_status_2groups == "Never") %>%
  pull(Tumor_Sample_Barcode)
ever_samples <- df_NSCLC %>%
  filter(smoking_status_2groups == "Ever") %>%
  pull(Tumor_Sample_Barcode)

genes <- c("KEAP1", "SMARCA4", "STK11", "NF1", "TP53", "CDKN2A", "ARID1A", "KMT2D", "KRAS", "NOTCH1")
```

# Univariate analysis for mutation status of driver genes

```{r }

# Function to perform Cox proportional hazards regression for smoking status
PerformSurvSmoking <- function(mydf, mycancertype) {
  # mydf <- df_NSCLC
  # mycancertype <- "NSCLC"
  df_res <- tibble(
    cancertype = mycancertype,
    sample_num = nrow(mydf),
    ever_num = NA_integer_,
    never_num = NA_integer_,
    hr_coxph = NA_real_,
    hr_coxph_conf_low = NA_real_,
    hr_coxph_conf_high = NA_real_,
    pval_coxph = NA_real_
  )

  df_res$ever_num[1] <- nrow(mydf %>% filter(smoking_status_2groups == "Ever"))
  df_res$never_num[1] <- nrow(mydf %>% filter(smoking_status_2groups == "Never"))

  fit <- coxph(Surv(OS_months, OS) ~ smoking_status_2groups + alcohol_status + Age + subtype, data = mydf)
  df_model_tmp <- broom::tidy(fit, exponentiate = TRUE, conf.int = TRUE)
  df_res$hr_coxph[1] <- df_model_tmp$estimate[df_model_tmp$term == "smoking_status_2groupsEver"]
  df_res$hr_coxph_conf_low[1] <- df_model_tmp$conf.low[df_model_tmp$term == "smoking_status_2groupsEver"]
  df_res$hr_coxph_conf_high[1] <- df_model_tmp$conf.high[df_model_tmp$term == "smoking_status_2groupsEver"]
  df_res$pval_coxph[1] <- df_model_tmp$p.value[df_model_tmp$term == "smoking_status_2groupsEver"]
  return(df_res)
}


ls_df_res <- vector("list", length(genes))
names(ls_df_res) <- genes
ls_df_res_wt <- vector("list", length(genes))
names(ls_df_res_wt) <- genes
ls_df_res_mut <- vector("list", length(genes))
names(ls_df_res_mut) <- genes

for (i in seq_along(genes)) {
  # i <- 1
  gene_i <- genes[i]
  print(gene_i)
  mut_samples_tmp <- df_NSCLCmut %>%
    filter(vep_Hugo_Symbol %in% gene_i) %>% 
    pull(Tumor_Sample_Barcode) %>% 
    unique()
  df_NSCLC_wt <- df_NSCLC %>% 
    filter(!(Tumor_Sample_Barcode %in% mut_samples_tmp))
  df_NSCLC_mut <- df_NSCLC %>% 
    filter(Tumor_Sample_Barcode %in% mut_samples_tmp)
  ls_df_res[[i]] <- PerformSurvSmoking(df_NSCLC, "NSCLC") %>% 
    mutate(gene = gene_i) %>% 
    dplyr::select(cancertype, gene, everything())
  ls_df_res_wt[[i]] <- PerformSurvSmoking(df_NSCLC_wt, "NSCLC") %>% 
    mutate(gene = gene_i) %>% 
    dplyr::select(cancertype, gene, everything())
  ls_df_res_mut[[i]] <- PerformSurvSmoking(df_NSCLC_mut, "NSCLC") %>% 
    mutate(gene = gene_i) %>% 
    dplyr::select(cancertype, gene, everything())
}

df_res_all <- bind_rows(ls_df_res)  
df_res_wt <- bind_rows(ls_df_res_wt)
df_res_mut <- bind_rows(ls_df_res_mut)

df_res_all %>% 
  write_tsv(str_glue("{outdir_table}/C-CAT_survival_OSfromCGP_smoking_comparison_NSCLC_all.tsv"))
df_res_wt %>% 
  write_tsv(str_glue("{outdir_table}/C-CAT_survival_OSfromCGP_smoking_comparison_NSCLC_wt.tsv"))
df_res_mut %>% 
  write_tsv(str_glue("{outdir_table}/C-CAT_survival_OSfromCGP_smoking_comparison_NSCLC_mut.tsv"))

```

# Smoking and mutation status pairwise comparison
```{r four groups survival analysis}

# Function to perform Cox proportional hazards regression for smoking status and mutation status
PerformSurvivalSmkMutPairwise <- function(mydf, mygene, mysamples) {

  mut_samples_tmp <- df_mut %>%
    filter(vep_Hugo_Symbol %in% mygene,
           Tumor_Sample_Barcode %in% mysamples) %>% 
    pull(Tumor_Sample_Barcode) %>% 
    unique()

  df_sample_tmp <- mydf %>% 
    mutate(mutation = case_when(
      Tumor_Sample_Barcode %in% mut_samples_tmp ~ "Mut",
      !(Tumor_Sample_Barcode %in% mut_samples_tmp) ~ "WT"
    )) %>%  
    mutate(smoking_status_2groups = factor(smoking_status_2groups, levels = c("Never", "Ever"))) %>%
    mutate(mutation = factor(mutation, levels = c("WT", "Mut"))) %>%
    mutate(smk_mut_4groups = case_when(
      Tumor_Sample_Barcode %in% mut_samples_tmp & Tumor_Sample_Barcode %in% never_samples ~ "Never-Mut",
      Tumor_Sample_Barcode %in% mut_samples_tmp & Tumor_Sample_Barcode %in% ever_samples ~ "Ever-Mut",
      !(Tumor_Sample_Barcode %in% mut_samples_tmp) & Tumor_Sample_Barcode %in% never_samples ~ "Never-WT",
      !(Tumor_Sample_Barcode %in% mut_samples_tmp) & Tumor_Sample_Barcode %in% ever_samples ~ "Ever-WT"
    )) 

  df_expand <- expand.grid(
    groupA = c("Never-WT", "Never-Mut", "Ever-WT", "Ever-Mut"),
    groupB = c("Never-WT", "Never-Mut", "Ever-WT", "Ever-Mut"),
    stringsAsFactors = FALSE
    ) %>%
    filter(groupA < groupB) %>% 
    mutate(gene = str_c(mygene, collapse = ",")) %>% 
    dplyr::select(gene, everything()) %>% 
    mutate(
      hr_coxph = NA_real_,
      hr_coxph_conf_low = NA_real_,
      hr_coxph_conf_high = NA_real_,
      pval_coxph = NA_real_
    )
          
  for (i in seq_len(nrow(df_expand))) {
    # i <- 2
    groupA_i <- df_expand$groupA[i]
    groupB_i <- df_expand$groupB[i]
    df_pair <- df_sample_tmp %>%
      filter(smk_mut_4groups %in% c(groupA_i, groupB_i))
    
    fit_tmp <- coxph(Surv(OS_months, OS) ~ smk_mut_4groups + alcohol_status + Age + PS_group + subtype , data = as.data.frame(df_pair))
    df_model_tmp <- broom::tidy(fit_tmp, exponentiate = TRUE, conf.int = TRUE)
    df_expand$hr_coxph[i] <- df_model_tmp$estimate[1]
    df_expand$hr_coxph_conf_low[i] <- df_model_tmp$conf.low[1]
    df_expand$hr_coxph_conf_high[i] <- df_model_tmp$conf.high[1]
    df_expand$pval_coxph[i] <- df_model_tmp$p.value[1]
  }

  return(df_expand)
}

df_res_STK11_CDKN2A <- PerformSurvivalSmkMutPairwise(df_NSCLC, c("STK11", "CDKN2A"), allsamples)

df_res_STK11_CDKN2A %>% 
  write_tsv(str_glue("{outdir_table}/C-CAT_survival_OSfromCGP_smoking_mutation_pairwise_comparison_STK11_CDKN2A.tsv"))
```

```{r sessioninfo}
sessionInfo()

```