---
title: "Driver fusion enrichment"
author: "Yosuke Mizukami"
date: "2025-11-06"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r library, message=FALSE, warning=TRUE}
library(tidyverse)
library(readxl)
library(lubridate)
library(broom)
library(cowplot)
theme_set(theme_cowplot())
library(RColorBrewer)
library(logging)
library(lawstat)
library(DescTools)
library(MASS)
library(ggrepel)
```

```{r source}
source("../../util/R/utils.R")
source("../../util/R/figure.R")
source("../../util/R/colors.R")
source("../../util/R/readin.R")
```

```{r make directory}
# make directory
outdir0 <- "result/2_C_CAT/1_pancan/3_rearrangement/2_1_driver_enrichment_q005"
outdir_table <- str_glue("{outdir0}/table")
dir.create(outdir_table, recursive = TRUE, showWarnings = FALSE)
outdir_pdf <- str_glue("{outdir0}/pdf")
dir.create(outdir_pdf, recursive = TRUE, showWarnings = FALSE)
```

# Prepare a driver list and identified fusions

```{r read data}

all_cancertypes_fct <- read_tsv("../../data/cancertype_fct_v2.tsv", col_names = "cancertype") %>%
  pull(cancertype) %>%
  intersect(unique(df$cancertype_CCAT)) 

df_fusion <- read_tsv("result/1_data_preparation/C_CAT_tissue/merged/merged_fusion_data.tsv") %>% 
  filter(is_mitel == TRUE) 
df_driver_fusion <- read_tsv("result/1_data_preparation/C_CAT_tissue/driver_creation/table/driver_fusion_genes.tsv")

df_driver_fusion %>% 
  filter(cancertype %in% all_cancertypes_fct) %>%
  count(cancertype) %>%
  complete(cancertype = all_cancertypes_fct, fill = list(n = 0)) %>% 
  mutate(cancertype = factor(cancertype, levels = all_cancertypes_fct)) %>%
  ggplot(aes(x = cancertype, y = n)) +
  geom_bar(stat = "identity") +
  labs(x = "Cancer type", y = "Number of driver fusion genes") +
  scale_y_continuous(expand = c(0, 0)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5), 
        aspect.ratio = 1/6,
        axis.title.y = element_text(size = 7))
ggsave(str_glue("{outdir_pdf}/num_driver_fusion_genes_per_cancertype.pdf"), width = 5, height = 5)

all_cancertypes_fct <- unique(df$cancertype_CCAT) %>% sort()

```

# Univariate analysis

```{r univariate analysis}

EvaluateRearrenrichment <- function(mycancertype, mycolname) {
  # mycancertype <- all_cancertypes_fct[[2]]
  # mycolname <- "Alcohol"
  df_filt <- df %>%
    filter(cancertype_CCAT == mycancertype) 
  samples0 <- df_filt %>%
    filter(!!sym(mycolname) == 0) %>%
    pull(Tumor_Sample_Barcode) %>%
    unique()
  samples1 <- df_filt %>%
    filter(!!sym(mycolname) == 1) %>%
    pull(Tumor_Sample_Barcode) %>%
    unique()
  
  genes <- df_driver_fusion %>% 
    filter(cancertype == mycancertype) %>% 
    pull(gene)
  
  df_rearr_agg <- tibble(
    gene = genes,
    num_alt_0 = NA_real_,
    num_alt_1 = NA_real_,
    num_wt_0 = NA_real_,
    num_wt_1 = NA_real_
  )
  
  for (i in seq_along(genes)) {
    gene_i <- genes[i]
    alt_samples0 <- df_fusion %>%
      filter(Tumor_Sample_Barcode %in% samples0 & str_detect(fusion1, gene_i)) %>%
      pull(Tumor_Sample_Barcode) %>%
      unique()
    alt_samples1 <- df_fusion %>%
      filter(Tumor_Sample_Barcode %in% samples1 & str_detect(fusion1, gene_i)) %>%
      pull(Tumor_Sample_Barcode) %>%
      unique()
    
    wt_samples0 <- setdiff(samples0, alt_samples0)
    wt_samples1 <- setdiff(samples1, alt_samples1)
    
    df_rearr_agg[i, "num_alt_0"] <- length(alt_samples0)
    df_rearr_agg[i, "num_alt_1"] <- length(alt_samples1)
    df_rearr_agg[i, "num_wt_0"] <- length(wt_samples0)
    df_rearr_agg[i, "num_wt_1"] <- length(wt_samples1)
  }
  
  offset <- 0.01
  df_rearr_fisher_res <- df_rearr_agg %>% 
    mutate(
      fisher_res = pmap(
        list(num_wt_0, num_alt_0, num_wt_1, num_alt_1),
        function(a, b, c, d) {
          mat <- matrix(c(a, b, c, d), nrow = 2)
          fisher.test(mat)
        }
      ),
      fisher_p = map_dbl(fisher_res, ~ .x$p.value),
      fisher_or = pmap_dbl(
        list(num_wt_0, num_alt_0, num_wt_1, num_alt_1),
        function(a, b, c, d) {
          ((a + offset) * (d + offset)) / ((b + offset) * (c + offset))
        }
      )
    ) %>%
    dplyr::select(-fisher_res) %>%
    mutate(
      cancertype = mycancertype,
      variable = mycolname
    )
  
  return(df_rearr_fisher_res)
}

ls_df_rearr_fisher_smoking <- vector("list", length(all_cancertypes_fct))
ls_df_rearr_fisher_alcohol <- vector("list", length(all_cancertypes_fct))

for (i in seq_along(all_cancertypes_fct)) {
  # i <- 1
  ls_df_rearr_fisher_smoking[[i]] <- EvaluateRearrenrichment(all_cancertypes_fct[[i]], "Smoking")
  ls_df_rearr_fisher_alcohol[[i]] <- EvaluateRearrenrichment(all_cancertypes_fct[[i]], "Alcohol")
}

RenameColnames <- function(ls_df_input, mycolname, terms) {
  # ls_df_input <- ls_df_rearr_fisher_smoking
  # mycolname <- "smoking"
  # terms <- c("never", "ever")
  
  df_input <- bind_rows(ls_df_input) %>%
    mutate(fisher_q_all = p.adjust(fisher_p, method = "BH"))
  
  # Define the new column names to match the required naming
  new_names <- c(
    str_glue("num_samples_alt_{terms[2]}"), # 1 → ever, male, excessive
    str_glue("num_samples_wt_{terms[2]}"),
    str_glue("num_samples_alt_{terms[1]}"), # 0 → never, female, non_excessive
    str_glue("num_samples_wt_{terms[1]}"),
    str_glue("fisher_or_{mycolname}"),
    str_glue("fisher_p_{mycolname}"),
    str_glue("fisher_q_all_{mycolname}")
  )
  
  old_names <- c(
    "num_alt_1",
    "num_wt_1",
    "num_alt_0",
    "num_wt_0",
    "fisher_or",
    "fisher_p",
    "fisher_q_all"
  )
  
  df_input2 <- df_input %>% dplyr::rename(!!!setNames(old_names, new_names))
  
  df_input_select <- df_input2 %>%
    dplyr::select(gene, cancertype, all_of(new_names))
  
  return(df_input_select)
}

df_rearr_fisher_smoking <- RenameColnames(ls_df_rearr_fisher_smoking, "smoking", c("never", "ever"))
df_rearr_fisher_alcohol <- RenameColnames(ls_df_rearr_fisher_alcohol, "alcohol", c("non_excessive", "excessive"))

df_rearr_fisher_uni <- df_rearr_fisher_smoking %>%
  left_join(df_rearr_fisher_alcohol, by = c("gene", "cancertype")) 

```

# Relationship with pack-years

```{r pack year}
df_rearr_smoking3groups <- df_rearr_fisher_uni %>%
  dplyr::select(gene, cancertype) %>%
  mutate(
    num_samples_alt_gePY20 = NA_real_,
    num_samples_wt_gePY20 = NA_real_,
    num_samples_alt_ltPY20 = NA_real_,
    num_samples_wt_ltPY20 = NA_real_,
    cochran_armitage_pvalue = NA_real_
  )

for (i in seq_len(nrow(df_rearr_smoking3groups))) {
  # i <- 1
  gene_i <- df_rearr_smoking3groups$gene[i]
  cancer_i <- df_rearr_smoking3groups$cancertype[i]
  
  samples_tmp <- df %>%
    filter(cancertype_CCAT == cancer_i) %>%
    pull(Tumor_Sample_Barcode) %>%
    unique()  
  df_fusion_tmp <- df_fusion %>%
      filter(Tumor_Sample_Barcode %in% samples_tmp & str_detect(fusion1, gene_i))
  never_samples <- df %>%
    filter(cancertype_CCAT == cancer_i) %>%
    filter(smoking_status_2groups == "Never") %>%
    pull(Tumor_Sample_Barcode)
  more20_samples <- df %>%
    filter(cancertype_CCAT == cancer_i) %>%
    filter(smoking_status_2groups == "Ever") %>%
    filter(packyear >= 20) %>%
    pull(Tumor_Sample_Barcode)
  less20_samples <- df %>%
    filter(cancertype_CCAT == cancer_i) %>%
    filter(smoking_status_2groups == "Ever") %>%
    filter(packyear < 20) %>%
    pull(Tumor_Sample_Barcode)
  alt_never_samples <- df_fusion_tmp %>%
    filter(Tumor_Sample_Barcode %in% never_samples) %>%
    pull(Tumor_Sample_Barcode) %>%
    unique()
  alt_more20_samples <- df_fusion_tmp %>%
    filter(Tumor_Sample_Barcode %in% more20_samples) %>%
    pull(Tumor_Sample_Barcode) %>%
    unique()
  alt_less20_samples <- df_fusion_tmp %>%
    filter(Tumor_Sample_Barcode %in% less20_samples) %>%
    pull(Tumor_Sample_Barcode) %>%
    unique()
  wt_never_samples <- setdiff(never_samples, alt_never_samples)
  wt_more20_samples <- setdiff(more20_samples, alt_more20_samples)
  wt_less20_samples <- setdiff(less20_samples, alt_less20_samples)
  
  df_rearr_smoking3groups[i, "num_samples_alt_gePY20"] <- length(alt_more20_samples)
  df_rearr_smoking3groups[i, "num_samples_wt_gePY20"] <- length(wt_more20_samples)
  df_rearr_smoking3groups[i, "num_samples_alt_ltPY20"] <- length(alt_less20_samples)
  df_rearr_smoking3groups[i, "num_samples_wt_ltPY20"] <- length(wt_less20_samples)
  
  matrix_tmp <- c(
    length(wt_never_samples),
    length(wt_less20_samples),
    length(wt_more20_samples),
    length(alt_never_samples),
    length(alt_less20_samples),
    length(alt_more20_samples)
  ) %>% 
    matrix(nrow = 3)
  
  colnames(matrix_tmp) <- c("Not altered", "Altered")
  rownames(matrix_tmp) <- c("Never", "Less_20", "More_20")
  res <- CochranArmitageTest(matrix_tmp)
  p_value <- res$p.value
  
  df_rearr_smoking3groups[i, "cochran_armitage_pvalue"] <- p_value
}

```

# Multivariate analysis

```{r multivariate analysis}
df_combinations <- df_rearr_fisher_uni %>%
  dplyr::select(gene, cancertype) 

ls_df_res_lm <- vector("list", nrow(df_combinations))
for (i in seq_len(nrow(df_combinations))) {
  # i <- 255
  gene_i <- df_combinations$gene[i]
  cancer_i <- df_combinations$cancertype[i]

  samples_tmp <- df %>%
    filter(cancertype_CCAT == cancer_i) %>%
    pull(Tumor_Sample_Barcode) %>%
    unique()
  
  df_fusion_tmp <- df_fusion %>%
    filter(Tumor_Sample_Barcode %in% samples_tmp & str_detect(fusion1, gene_i))
  
  df_subset <- df %>%
    mutate(smoking_status_2groups = factor(smoking_status_2groups, levels = c("Never", "Ever"))) %>%
    mutate(alcohol_status = factor(alcohol_status, levels = c("FALSE", "TRUE"))) %>%
    filter(cancertype_CCAT == cancer_i) %>%
    mutate(Alteration = if_else(Tumor_Sample_Barcode %in% df_fusion_tmp$Tumor_Sample_Barcode, 1, 0)) 

  model_comb_age <- glm(Alteration ~ smoking_status_2groups + alcohol_status + Age, data = df_subset, family = binomial)
  
  df_model_comb_age <- broom::tidy(model_comb_age)
  df_row_comb_age <- df_model_comb_age %>% 
    filter(term == "smoking_status_2groupsEver")
  df_alcohol_row_comb_age <- df_model_comb_age %>% 
    filter(term == "alcohol_statusTRUE")
  
  ls_df_res_lm[[i]] <- tibble(
    gene = gene_i,
    cancertype = cancer_i,
    OR_smoking_multivar_alcsmkage = exp(df_row_comb_age$estimate),
    pval_smoking_multivar_alcsmkage = df_row_comb_age$p.value,
    OR_alcohol_multivar_alcsmkage = exp(df_alcohol_row_comb_age$estimate),
    pval_alcohol_multivar_alcsmkage = df_alcohol_row_comb_age$p.value,
  )
}

df_rearr_fisher_multi0 <- bind_rows(ls_df_res_lm)

df_rearr_fisher_multi <- df_rearr_fisher_multi0 %>%
  mutate(
    qval_all_smoking_multivar_alcsmkage = p.adjust(pval_smoking_multivar_alcsmkage, method = "BH"),
    qval_all_alcohol_multivar_alcsmkage = p.adjust(pval_alcohol_multivar_alcsmkage, method = "BH")
  )
  
df_fisher_merged <- df_rearr_fisher_uni %>%
  left_join(df_rearr_smoking3groups, by = c("gene", "cancertype")) %>%
  left_join(df_rearr_fisher_multi, by = c("cancertype", "gene" = "gene")) %>%
  left_join(df_driver_fusion, by = c("gene" = "gene", "cancertype" = "cancertype")) %>%
  dplyr::select(gene, cancertype, everything())

df_fisher_merged %>% 
  write_tsv(str_glue("{outdir_table}/driver_rearrangement_enrichment_univariate_multivariate.tsv"))

```


```{r sessioninfo}

sessionInfo()

```